GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:613: UserWarning: Checkpoint directory /home/tim/JetNN/jetnn/runners/wandb/run-20230706_153220-v7q3y6b1/files exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [6]
  | Name     | Type                           | Params
------------------------------------------------------------
0 | _encoder | MethodNameMyTransformerEncoder | 51.0 M
1 | _decoder | MethodNameTransformerDecoder   | 85.2 M
2 | _metrics | MetricCollection               | 0
3 | _loss    | SequenceCrossEntropyLoss       | 0
------------------------------------------------------------
136 M     Trainable params
0         Non-trainable params
136 M     Total params
544.435   Total estimated model params size (MB)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19400/19400 [00:00<00:00, 358748.31it/s]
  0%|                                                                                                                                                                                                                                                 | 0/19400 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                                                                    | 0/19400 [00:00<?, ?it/s]
  File "/home/tim/JetNN/jetnn/runners/run_methodnaming.py", line 142, in <module>
    train(config)
  File "/home/tim/JetNN/jetnn/runners/run_methodnaming.py", line 108, in train
    trainer.fit(model=model, datamodule=data_module)
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
            ^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
            ^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/tim/JetNN/jetnn/data_processing/plain_code_ast_method/plain_code_ast_dataset.py", line 68, in __getitem__
    tokens_split = self._code_tree.process_code(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/JetNN/jetnn/data_processing/tree_code_representation/my_code_tree.py", line 133, in process_code
    self._tree_sitter.process_code(java_code)
  File "/home/tim/JetNN/jetnn/data_processing/tree_code_representation/my_tree_sitter.py", line 24, in process_code
    self.init()
  File "/home/tim/JetNN/jetnn/data_processing/tree_code_representation/my_tree_sitter.py", line 14, in init
    Language.build_library(
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/tree_sitter/__init__.py", line 41, in build_library
    source_mtimes = [path.getmtime(__file__)] + [
                                                ^
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/tree_sitter/__init__.py", line 42, in <listcomp>
    path.getmtime(path_) for path_ in source_paths
    ^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 55, in getmtime
FileNotFoundError: [Errno 2] No such file or directory: '../tree-sitter-java/src/parser.c'